### PR TITLE
Flatpak: update MetaInfo with historical release notes

### PR DESCRIPTION
**Pull request by cassidyjames**
These came from the [Itch devlog](https://hhoneysoftware.itch.io/rota/devlog), lightly adapted for the limited HTML-like release notes format for MetaInfo.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@HarmonyHoney I've rebased this to the branch5 branch, so it should be good to go. This corrects the fact that Flathub currently shows `0.0.0` as the latest release at https://flathub.org/apps/net.hhoney.rota

**Comment by cassidyjames** [comment]
I've included #12 in this PR as well as long as we're updating the metainfo for Flathub; I can revert that if you'd prefer to merge things separately.

**Comment by cassidyjames** [comment]
@HarmonyHoney okay, rebased again against the latest changes.

**Comment by HarmonyHoney** [comment]
merged, thank you ! (-=

**Pull request merged**
